02WB/app/manager/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Email, Length, Regexp, EqualTo
from wtforms import TextAreaField, SelectField
from app.models import User
from app.models import Role
from wtforms.validators import ValidationError

class EditUserForm(FlaskForm) :
    email = StringField(label='邮箱', validators=[DataRequired(), Email(), Length(1, 128)])
    name = StringField(label='昵称', validators=[DataRequired(), Length(1, 128)])
    location = StringField(label='位置', validators=[DataRequired(), Length(1, 64)])
    about_me = TextAreaField(label='签名', validators=[DataRequired(), Length(1, 256)])
    # coerce=int 选择产生的是一个数字
    role_id = SelectField(label='角色', coerce=int)
    confirmed = BooleanField(label='邮箱激活')
    password = PasswordField(label='密码')
    password_again= PasswordField(label='确认密码', validators=[EqualTo('password', '两次密码不一致')])
    submit = SubmitField(label='确认编辑')

    def __init__(self, *args, **kwargs):
        super(EditUserForm, self).__init__(*args, **kwargs)
        self.role_id.choices = [(role.id, role.name) for role in Role.query.all()]


02WB/app/manager/__init__.py
from flask import Blueprint

manager = Blueprint('manager', __name__)

from . import views

02WB/app/manager/views.py
from flask import render_template, url_for, redirect, flash, request
from flask_login import login_required, current_user

from app import db
from . import manager
from app.decorators import decorator_admin, decorator_permission
from app.models import Permission, Comments, News
from .forms import EditUserForm
from flask import abort
from app.models import User

@manager.route('/edit_user', methods=['GET', 'POST'])
@decorator_admin
def edit_user() :
    id = request.args.get('id')
    if id is None :
        abort(404)
    user = User.query.filter_by(id=id).first()
    if user is None :
        abort(404)

    form = EditUserForm()
    if form.validate_on_submit() :
        user.name = form.name.data
        user.confirmed = form.confirmed.data
        user.location = form.location.data
        user.role_id = form.role_id.data
        user.about_me = form.about_me.data
        if len(form.password.data) != 0 :
            user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('main.user_info', id=user.id))

    form.name.data = user.name
    form.email.data = user.email
    form.location.data = user.location
    form.role_id.data = user.role_id
    form.about_me.data = user.about_me
    form.confirmed.data = user.confirmed
    return render_template('manager/edit_user.html', form=form)

@manager.route('/index')
@decorator_admin
def index() :
    page = request.args.get('page', type=int, default=1)
    comments = Comments.query.group_by(Comments.news_id).all()
    paginate = Comments.query.order_by(Comments.id.desc()).paginate(page=page, per_page=5, error_out=False)

    return render_template('manager/edit_comments.html',comments = comments,paginate=paginate)

@manager.route('/manager_comment')
@decorator_permission(Permission.MODE_COMMENT)
def manager_comment() :
    return 'i am moderator or admin'
@manager.route('/delete_comments')
@login_required
def delete_comments() :
    cid = request.args.get('cid')
    if cid is None:
        abort(404)
    comments = Comments.query.filter_by(id=cid).first()
    if comments is None:
        abort(404)

    if current_user == comments.user or current_user.is_admin() :
        db.session.delete(comments)
        db.session.commit()

    return redirect(url_for('manager.index',nid = comments.news_id))

02WB/app/templates/manager/edit_comments.html
{% extends 'base.html' %}

{% block page_content %}
<h2><small>管理评论界面!</small>&nbsp;&nbsp;{{current_user.name}}</h2>
{% endblock %}

{% block page_content1 %}

    {% for comments in paginate.items %}

        <a><font size="4" color="#191970" style="margin-right: 300px;">{{comments.news.title}}</font></a><br>
        <a href="{{url_for('manager.delete_comments', cid=comments.id)}}">
                        删除
                    </a>

        <div class="alert alert-success" role="alert">{{comments.user.name}}<br>{{moment(comments.timestamp).fromNow()}}:<br>{{comments.body}}</div>
    {% endfor %}
 <div align="center">
        {% import 'macro/macro.html' as macro %}
        {{macro.pagination_widget(paginate, 'manager.index')}}
    </div>
{% endblock %}

02WB/app/templates/manager/edit_user.html
{% extends 'base.html' %}

{% block page_content %}
<h2><small>欢迎!</small>&nbsp;&nbsp;{{current_user.name}}</h2>
{% endblock %}

{% block page_content1 %}
    {% import 'bootstrap/wtf.html' as wtf %}
    {{ wtf.quick_form(form) }}
{% endblock %}